### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by PhilipGarnero** [vbabiy/django-pipeline-compass#10]
Hello there !

I'm currently having an issue in a prod environment with pipeline-compass.
Whenever I try to launch my app in debug or collectstatic, pipeline raises an import error:
`no module named compiler`

Any idea on how to fix this ?
Thanks

**Comment by vbabiy** [comment]
Do you have a stack trace?

**Comment by PhilipGarnero** [comment]
Here's the traceback I get :

```
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/application/ovh-var/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/application/ovh-var/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/application/ovh-var/python/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/application/ovh-var/python/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/application/ovh-var/python/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/application/ovh-var/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle_noargs
    collected = self.collect()
  File "/application/ovh-var/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 118, in collect
    for original_path, processed_path, processed in processor:
  File "/application/ovh-var/python/lib/python2.7/site-packages/pipeline/storage.py", line 32, in post_process
    packager.pack_stylesheets(package)
  File "/application/ovh-var/python/lib/python2.7/site-packages/pipeline/packager.py", line 94, in pack_stylesheets
    variant=package.variant, **kwargs)
  File "/application/ovh-var/python/lib/python2.7/site-packages/pipeline/packager.py", line 103, in pack
    paths = self.compile(package.paths, force=True)
  File "/application/ovh-var/python/lib/python2.7/site-packages/pipeline/packager.py", line 97, in compile
    return self.compiler.compile(paths, force=force)
  File "/application/ovh-var/python/lib/python2.7/site-packages/pipeline/compilers/__init__.py", line 49, in compile
    return list(executor.map(_compile, paths))
  File "/application/ovh-var/python/lib/python2.7/site-packages/concurrent/futures/_base.py", line 549, in map
    yield future.result()
  File "/application/ovh-var/python/lib/python2.7/site-packages/concurrent/futures/_base.py", line 397, in result
    return self.__get_result()
  File "/application/ovh-var/python/lib/python2.7/site-packages/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
ImportError: No module named compiler
```

**Comment by bbarr** [comment]
I am having a similar issue with the React/JSX compiler.. Did this have an outcome?
